### ISSUE TITLE
The Hide button for the table of contents/filter panel still disappears when zooming in

### ISSUE THREAD

**Issue by mraccess77** [w3c/wai-wcag-quickref#107]
Go the page with 1024x768 or 800x600.
Starting zooming in toward 200%
Notice the Hide button for the table of contents/filter panel will disappear and you can't hide the panel.

**Comment by yatil** [comment]
Yes, this is the mobile view. There is no way to hide the panel in the mobile view at the moment. I take that as a feature request. Thank you.

**Comment by mraccess77** [comment]
Sure, feature request -- no need to hold up anything!
