### ISSUE TITLE
Extra failures on SC 2.4.6

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-wcag-quickref#110]
[SC 2.4.6](http://w3c.github.io/wai-wcag-quickref/#navigation-mechanisms-descriptive) has Failures [F63](http://www.w3.org/TR/WCAG20-TECHS/F63.html) and [F89](http://www.w3.org/TR/WCAG20-TECHS/F89.html) incorrectly associated with it.

**Comment by yatil** [comment]
Related to #26.

**Comment by yatil** [comment]
Interesting, they are [not in the JSON file](https://github.com/w3c/wai-wcag-quickref/blob/gh-pages/_data/wcag2.json#L3815) so I have to see where that information comes from.
