### ISSUE TITLE
Suggested changes to Tasks filter panel

### ISSUE THREAD

**Issue by MarcusJT** [w3c/wai-wcag-quickref#12]
- Name should be "Roles" not "Tasks"
- "Development" vs "Front-End Development" not clear, the latter is a subset of the former. Perhaps former should be "Back-End Development"? If not then what is it?
- Options should be listed in a different order, I suggest Content Strategy, User Experience, Design, Development, Front-End Development

**Comment by yatil** [comment]
Hi Marcus, thanks for the feedback. 

We did some user testing in the meantime and are streamlining the filters according to those results.

Best, Eric
