### ISSUE TITLE
The "show all SC's and Techniques" view leaves the techniques collapsed

### ISSUE THREAD

**Issue by DavidMacDonald** [w3c/wai-wcag-quickref#120]
Let's provide one button that opens EVERYTHING. So the user can do a CTRL+F on the page and look for things.

**Comment by yatil** [comment]
There is a button in the “contents” tab.

**Comment by DavidMacDonald** [comment]
OK... 
hmmm wonder if saying "Expand ALL Techniques" would help it be more discoverable...

**Comment by DavidMacDonald** [comment]
You know where I got confused is in the yellow highlighting at the top it said "showing all SC and techniques," but they were collapsed... I figured if it said that, that's where the button would be, would it make sense to put a button there, or move it there?

**Comment by yatil** [comment]
I tried to have it there but that is the status of the filters and that button is not filtering anything out (or in). Another possibility would be above the main content, but that would mean it would scroll away which is also not too useful. That button is hard to place.

**Comment by DavidMacDonald** [comment]
I understand... maybe just a note in the status bar about where to find it... such as "To expand all techniques, use the button on the top of the left menu" there might be a better shorter way to say that.

**Comment by yatil** [comment]
I’d rather not add more text to the status bar, to be honest. There is much going on there at the moment. I try to think about that some more…

**Comment by yatil** [comment]
Hi David,

as this was a last-minute addition and there is some confusion and discussion around it, I have removed the button for now. We will check back in EO to find a good place for the button and reintroduce it as soon as possible.

Best, Eric

**Comment by yatil** [comment]
<del>Three</del><del><ins>Four</ins></del><ins>Five</ins> Approaches:
- https://w3c.github.io/wai-wcag-quickref/button-1.html
  - Pros: Near main content, not in context of other interaction elements.
  - Cons: Hides from view when scrolling, slightly odd position.
- https://w3c.github.io/wai-wcag-quickref/button-2.html
  - Pros: Related to “Contents”, stays visible on scrolling.
  - Cons: Slightly odd position, you probably won’t find it if you come to the document with the filters column open.
- https://w3c.github.io/wai-wcag-quickref/button-3.html (Disregard the gray background)
  - Pros: Stays visible on scroll, manipulates the content below.
  - Cons: Slightly odd position: Share, which is an “outgoing” feature prior to something concerning only this document. Less space for status.
- https://w3c.github.io/wai-wcag-quickref/button-4.html (Disregard the gray background)
  - Pros: Stays visible on scroll, manipulates the content below.
  - Cons: Slightly better position than 3. Less space for status.
- https://w3c.github.io/wai-wcag-quickref/button-5.html (Disregard the gray background)
  - Pros: Stays visible on scroll, manipulates the content below.
  - Cons: Slightly better position than 3. Less space for status.

**Comment by yatil** [comment]
The group voted for approach 5.
