### ISSUE TITLE
Macbook Safari, yellow box big.

### ISSUE THREAD

**Issue by DavidMacDonald** [w3c/wai-wcag-quickref#121]
In Safari the yellow box at the top seems big and all lettering is on left side, in 5 rows...on Mac

**Comment by DavidMacDonald** [comment]
The text "Show less tags" should probably say "Show fewer tags" for proper English grammar. and that text could have a bit more space around it.

**Comment by yatil** [comment]
Hi David, can you check your Safari version? It should work in current versions.

(I have however noted a sub-optimal breakpoint in narrow-ish but not really totally narrow windows.)
