### ISSUE TITLE
Missing a link from SC 1.4.8 to an existing technique page G204 - currently says "future link"

### ISSUE THREAD

**Issue by gitdeepsix** [w3c/wai-wcag-quickref#126]
In SC 1.4.8, the first technique for the Fifth Requirement is currently;

> Not interfering with the user agent's reflow of text as the viewing window is narrowed (future link)

Should this not be linked to G204 (as it is in the first technique for the Second Requirement)?

**Comment by yatil** [comment]
Hi, good catch. I will relay this to the WCAG people who provide the data to this tool.
