### ISSUE TITLE
Back button does not go back

### ISSUE THREAD

**Issue by julezrulez** [w3c/wai-wcag-quickref#128]
If I click on an external link to i.e. [https://www.w3.org/WAI/WCAG20/quickref/#qr-content-structure-separation-programmatic]  the back-button won't bring me back to the page I came from.
(Tested in Chrome version 49)

**Comment by yatil** [comment]
This is – surprisingly – **not** intended behavior. Looks like there is something going on with the URL reading portion of the document. Very interesting.

**Comment by yatil** [comment]
It looks like the history of the browser is polluted by different states of the tool… -.- 
![](https://cloud.githubusercontent.com/assets/58862/14639910/51b679ce-063f-11e6-9c2d-f63c637a66f9.png)

**Comment by DavidMacDonald** [comment]
today in Chrome, was on WCAG doc and clicked how to meet. Clicked back button to return to WCAG but it didn't work. Wen back and googled WCAG 2 and started again...

**Comment by yatil** [comment]
Hi @DavidMacDonald, I'm still investigating this. Sorry for the inconvenience.
