### ISSUE TITLE
Deeplinks to sufficient and advisory techniques and failures

### ISSUE THREAD

**Issue by julezrulez** [w3c/wai-wcag-quickref#131]
Links like https://www.w3.org/WAI/WCAG20/quickref/#text-equiv-all-tech-optional-head don't bring you directly to this certain subject in the quickref anymore.

In the Dutch Web Guidelines many links were made directly to every technique/failure.
Some of these links:
https://www.w3.org/WAI/WCAG20/quickref/#keyboard-operation-keyboard-operable-tech-optional-head
https://www.w3.org/WAI/WCAG20/quickref/#keyboard-operation-keyboard-operable-failures-head
https://www.w3.org/WAI/WCAG20/quickref/#keyboard-operation-keyboard-operable-sufficient-head
This is done for every succes criterium. I counted about 180 deeplinks to the Quickref.

You can find an example of a none working link here:
http://versie2.webrichtlijnen.nl/documentatie/2.1.1/#w-2-1-1-meet-nl
It's the first English link in the second paragraph "How to meet..."

**Comment by yatil** [comment]
Hi @julezrulez 

thanks for reporting this. I will look into providing the headers again, along with the JavaScript that is needed to expand the section.

There actually is a way to link to the contents, which is using http://www.w3.org/WAI/WCAG20/quickref/?showtechniques=111#sc-111-sufficient

**Comment by yatil** [comment]
Sorry, we never got around to doing this, and I guess after three years it is moot now. If this is still an issue, feel free to re-open the issue but I cannot promise to address this in any quick fashion.

**Comment by julezrulez** [comment]
As far as I know you did fixed this already (didn't know the issue was still open). And if it was a problem it was solved by the Dutch government. They deleted the whole website where the links came from.
Thanks anyway!

**Comment by yatil** [comment]
@julezrulez Well, that is one way to “solve” things ;-)
