### ISSUE TITLE
Using URL fragments results in obscured content

### ISSUE THREAD

**Issue by webstacker** [w3c/wai-wcag-quickref#135]
When linking to a specific section the sticky yellow bar obscures the content:

![Obscured content](https://pbs.twimg.com/media/Cs9v1kYWIAAlsq3.jpg:large)

[https://www.w3.org/WAI/WCAG20/quickref/#qr-meaning-doc-lang-id](https://www.w3.org/WAI/WCAG20/quickref/#qr-meaning-doc-lang-id)

Same result across the following OS/Browser combinations:

Windows 8.1
Firefox 49.0
Chrome 53.0.2785.116
Internet explorer 11.0.9600.18427

OS X El Capitan
Firefox 48.0.1
Chrome 53.0.2785.116
Safari 9.1.2

**Comment by yatil** [comment]
Thanks for the excellent bug report, Stephen. It looks indeed as if we have a regression there. (Isn’t it always the most fun when things used to work?)

**Comment by yatil** [comment]
I have made changes and they should be live on GitHub:

http://w3c.github.io/wai-wcag-quickref/#qr-meaning-doc-lang-id
