### ISSUE TITLE
Quick Ref - Share links with incorrect Aria-Label

### ISSUE THREAD

**Issue by HerinHentry** [w3c/wai-wcag-quickref#143]
Quick Ref Share links have incorrect reference set. Please see the code and screenshot below.

Tested in windows 7 / Firefox and IE.

<a href="#qr-text-equiv-all" aria-label="Share Link to the section “ Back to top”"><svg class="i-share" aria-hidden="true"><use xlink:href="img/icons.svg#i-share"/></svg> SHARE</a>

![image](https://cloud.githubusercontent.com/assets/15111528/23636172/0b547fbc-0328-11e7-9225-c05d50231a4d.png)

**Comment by yatil** [comment]
How embarrassing. Luckily that is easy to fix.
