### ISSUE TITLE
1.3.1 Failures listing the failure related to 4.1.2

### ISSUE THREAD

**Issue by HerinHentry** [w3c/wai-wcag-quickref#144]
F68: Failure of Success Criterion 4.1.2 due to a user interface control not having a programmatically determined name is listed in 1.3.1

![image](https://cloud.githubusercontent.com/assets/15111528/23922585/09502088-0957-11e7-9942-b3d365df4ecf.png)

**Comment by yatil** [comment]
Thanks @HerinHentry.

Looks like this got somehow into the source file: https://github.com/w3c/wai-wcag-quickref/blob/gh-pages/_data/wcag2.json#L1610

/cc @michael-n-cooper
