### ISSUE TITLE
QuickRef - Multiple Complementary Landmarks

### ISSUE THREAD

**Issue by HerinHentry** [w3c/wai-wcag-quickref#145]
There are multiple Complementary landmarks in QuickRef. Would be easy for element list user if they have unique labels.

![complementary](https://cloud.githubusercontent.com/assets/15111528/25213689/8fb7a6ba-25d5-11e7-94c5-e2e64c4d2c14.PNG)

**Comment by HerinHentry** [comment]
Reference : https://www.w3.org/TR/WCAG20-TECHS/ARIA11.html

**Comment by yatil** [comment]
Thanks @HerinHentry! That’s a bug. I’ll try to address it in the next version of the tool.
