### ISSUE TITLE
Failures issues

### ISSUE THREAD

**Issue by kospl** [w3c/wai-wcag-quickref#146]
Related to https://github.com/w3c/wai-wcag-quickref/issues/144

Issues with Failures for criterias:

- 1.2.2: wrong order: F75, 74

- **1.3.1: F68 - not related**

- 1.3.2: wrong order: F34, 33, 32, 49, 1

- 2.1.1: wrong order: F54, 55, 42

- **2.1.3: missing F42**

- 2.2.2: wrong order: F16, 47, 4, 50, 7

- 3.1.5: wrong order: F60, 61, 9, 22, 52, 41

- **4.1.2:** wrong order: F59, 15, 20, 68, 79, 86, 89; **missing F42**

**Comment by yatil** [comment]
@kospl Thanks for finding those.  

@michael-n-cooper Can you check that the data in the [wcag2.json](https://github.com/w3c/wai-wcag-quickref/blob/gh-pages/_data/wcag2.json) is generated correctly? (I think we need to update the quickref at some time anyway.)

I’ll take care of the sorting.

**Comment by yatil** [comment]
This was fixed in cb3e3f6.
