### ISSUE TITLE
Highlighting of SC in the left navigation

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-wcag-quickref#151]
I get a very odd thing happening in the navigation in both Chrome and FF on Windows. When I click on a SC in the left hand nav, the main content scrolls to that SC, but in the nav it highllights the SC above the one I selected. So the content is correct, but the highlighting in the nav is not correct. 

For example, if I click on "2.2.3 No Timing"​ in the left nav, the main content window auto-scrolls to 2.2.3 No Timing, but in the nav "2.2.2 Pause Stop Hide" is the SC that is highlighted.

**Comment by yatil** [comment]
Thanks @bakkenb! Looks like we are just a few pixels too far up to have the navigation changed :-o

Example link: https://www.w3.org/WAI/WCAG20/quickref/#time-limits-no-exceptions

I’ll take a look at it.

**Comment by yatil** [comment]
Hi @bakkenb, I looked into it and it should now be fixed.

Best,
Eric
