### ISSUE TITLE
Consider including ("Quick Reference") in heading & title

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-wcag-quickref#154]
from https://lists.w3.org/Archives/Public/wai-eo-editors/2018Jan/0002.html:

> I have attended a number of webinars and conferences where the page How to Meet WCAG 2.0 is referred to as the "Quick Reference Guide." This has caught me off guard as there is no place on the page that titles this page as "Quick Reference Guide."  It is described as "A customizable quick reference" which is not a title or heading.
Do you know why this page is referenced as such? If this is the common vernacular in the community, perhaps a heading "Quick Reference Guide" could be added to the page for those with cognitive disabilities.

**Comment by shawna-slh** [comment]
/me wouldn't call this a bug, but if @yatil wants to, that's fine with me)

**Comment by bakkenb** [comment]
He added that "bug" label so we would keep bugging him about it.  :)

**Comment by yatil** [comment]
As the maintainer of this project, I declared it a bug as I don’t want to publish an iteration without this issue decided :-)

FWIW my two cents:

- Rename the Quickref to ”WCAG 2 Quick Reference”
- “How to Meet” for me never really captured the nature of this application as it just displays you a subset of WCAG and then links out to techniques. 
- I would put _Formerly: How to Meet WCAG 2_ in the subtitle.

I really don’t feel strongly, but the name is used in specifications, so there might be a lot of ramifications that I don’t see. It is relatively easy to change here, so I have the feeling that this needs to be decided elsewhere. A compromise would be “How To Meet WCAG 2 Quick Reference” but that really is a mouth full.

**Comment by bakkenb** [comment]
Any way to get a list of where it is referenced?

**Comment by shawna-slh** [comment]
You are correct that the issue is that "How to Meet" is codified in WCAG 2.0. That means we can't/shouldn't totally change that.

I do think we can add "Quick Reference" to it. (even though there are some concerns with "quick" -- but that is the common name and URI)

Some options:
* How To Meet WCAG 2 Quick Reference
* How To Meet WCAG 2 (Quick Reference)
* How To Meet WCAG 2 "Quick Reference"
* How To Meet WCAG 2 ("Quick Reference")

We should also consider the subtitle / description, which is currently
"A customizable quick reference to Web Content Accessibility Guidelines (WCAG) 2.0 requirements (success criteria) and techniques."

**Comment by bakkenb** [comment]
So far I like:
> How To Meet WCAG 2 (Quick Reference)

Suggestion on subtitle/description:
> Quick Reference is a customizable filter and view tool of the Web Content Accessibility Guidelines (WCAG) 2.0 requirements (success criteria) and techniques.

**Comment by yatil** [comment]
I would argue against setting ”Ouick Reference” in quotes. Takes from the impact. Maybe just say Reference instead of “Quick Reference”? We could change the URL for 2.1.

**Comment by shawna-slh** [comment]
Proposal from Shawn, Eric, Sharron, Brent:
Try to get this through without much further discussion. :-)

Title: 
> How  To Meet WCAG 2 (Quick Reference)

No change to description.

See it in place: https://w3c.github.io/wai-wcag-quickref/

Get EOWG and AG WG approval.

**Comment by vavroom** [comment]
I like this approach, as per survey.

**Comment by nrhsinclair** [comment]
This approach seems to work fine.

**Comment by shawna-slh** [comment]
EOWG approval in survey: https://www.w3.org/2002/09/wbs/35532/EO-Weekly-23-Feb-2018/results#xq7

Pending AG WG approval.

**Comment by bakkenb** [comment]
Email sent to AGWG Chairs for Approval of Proposal - 07 March 2017

**Comment by bakkenb** [comment]
AGWG Chairs have approved [proposed title update](https://w3c.github.io/wai-wcag-quickref/). They will send an FYI to their working group for viability

See [AGWG Chair email response](https://lists.w3.org/Archives/Public/public-eo-plan/2018JanMar/0027.html)

**Comment by shawna-slh** [comment]
@yatil -- would it work to update this when you're in it over the next week+

So you don't have to figure out from above, here is the resolution:

Add (Quick Reference) to the title and heading 1.

> How to Meet WCAG 2 (Quick Reference)

**Comment by yatil** [comment]
Uploaded.
