### ISSUE TITLE
quickref for 1.3.5 ambiguous

### ISSUE THREAD

**Issue by stevefaulkner** [w3c/wai-wcag-quickref#159]
> 1.3.5 Identify Input Purpose Level AA(Added in 2.1)
> The purpose of each input field collecting information about the user can be programmatically determined when:

the description for 1.3.5 stops at "when:" Suggest either removing 

> The purpose of each input field collecting information about the user can be programmatically determined when:

or adding

> - The input field serves a purpose identified in the Input Purposes for User Interface Components section; and
> - The content is implemented using technologies with support for identifying the expected meaning for form input data.
>

**Comment by yatil** [comment]
Thanks!

**Comment by yatil** [comment]
@michael-n-cooper The two conditions are not included in the JSON file. Can you add them?

**Comment by yatil** [comment]
Hand-fixed in https://github.com/w3c/wai-wcag-quickref/commit/a64016d103104746b3a480e01ed6fd7c12d8e017
