### ISSUE TITLE
Success Criteria Layout

### ISSUE THREAD

**Issue by yatil** [w3c/wai-wcag-quickref#16]
<p>The Success Criteria layout was changed to be more clean and more distinct in comparison to the Guidelines.</p>

**Comment by shawna-slh** [comment]
I suggest the Levels are not in italics.

**Comment by shawna-slh** [comment]
Having the SC numbers on a darker gray adds a slight complexity to the visual design that I'm not sure is helpful. I think they stand out enough with the indentation as you have it. I think it would be better to have the same gray background behind the numbers and the text.

**Comment by iadawn** [comment]
I would prefer to see more use of negative space as a method for separating SC and Guidelines. The lines are ok, but I think en masse there is quite a lot of visual noise to work through to get to the content. A little more space between thing, may help to reduce this.

**Comment by bakkenb** [comment]
I like the layout. I think it is a lot cleaner than what was presented before. I especially like how it looks when you have selected one of the tags and the irrelevant criteria are collapsed and muted.

I would respectfully disagree with Shawn about changing SC # and Text to one lighter gray background color. If you do that it will look too similar to the Show Techniques button. I am in favor of leaving the coloring the way it is. 

I really like the placement of the Understanding link. Perfect location.

**Comment by yatil** [comment]
SC criteria, including changes outlined above, were received well in the meetings, for example [July 17th](http://www.w3.org/2015/07/17-eo-minutes.html#item09).
