### ISSUE TITLE
Clearly separate WCAG Version drop-down from other text

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-wcag-quickref#160]
<img width="204" alt="wimpy-border" src="https://user-images.githubusercontent.com/6991814/40990719-57736a3e-68b7-11e8-9e48-86a198b3241f.png">

Drop-down text visually runs into the text below it -- very hard to tell what is in the drop-down and not.

Needs much more clear separation. 

Maybe make a very strong (probably extra-thick and dark) border at the bottom of the WCAG Version drop-down box. Possibly extra space, too?

Thanks!

**Comment by yatil** [comment]
This is the default styling of the operating system. Other operating systems do a better job here. 
![Example: macOS](https://user-images.githubusercontent.com/58862/40991530-5cefa454-68f4-11e8-88f8-cdc4f4c3ec6c.png)

I see what I can do, but those native form elements are hard to style.

**Comment by yatil** [comment]
@slhenry Only so I can make sure it works in the browser you are using, too: Can you tell me what you use (or if it is a general issue on Windows. (there should at least be a border underneath “Only 2.1…”

**Comment by shawna-slh** [comment]
grumble, grumble, grumble browsers!

Chrome:
<img width="204" alt="wimpy-border" src="https://user-images.githubusercontent.com/6991814/40993054-195cf4b6-68be-11e8-9fec-c33aef362568.png">


Firefox:
<img width="262" alt="ff-wimpy-border" src="https://user-images.githubusercontent.com/6991814/40993058-1cb50dd8-68be-11e8-96ca-a5bfc4791000.png">

IE:
<img width="298" alt="ie-wimpy-border" src="https://user-images.githubusercontent.com/6991814/40993068-2758fe5c-68be-11e8-98ba-9ec7ec190b1c.png">


<hr>

p.s. Keep in mind that I have some OS and browser settings to increase readability and legibility for low vision. Unfortunately, I haven't kept track of them all, and so can't easily turn them all off for testing. :-/

Feel free to close this GitHub issue if we're calling it a browser ACCESSIBILITY BUG that's not reasonably worked-around.

**Comment by yatil** [comment]
In my Windows 8.1 testing environment, chrome at least has a bottom border. I looked into fiking it with CSS but there seems no obvious way. 

![screen shot 2018-06-06 at 11 39 14](https://user-images.githubusercontent.com/58862/41030408-9137d4a4-697e-11e8-92de-41e14eaf766b.png)
