### ISSUE TITLE
Success criterion 2.3.1 lacks level

### ISSUE THREAD

**Issue by massic80** [w3c/wai-wcag-quickref#163]
There is no A, AA or AAA level in https://www.w3.org/WAI/WCAG21/quickref/#three-flashes-or-below-threshold

**Comment by yatil** [comment]
Hi @massic80. Someone *cough* I *cough* did not upload the corrected file. Please try to reload again. (Note that the server can be very insistent in serving cached data, so it might take a couple of minutes or so to show up.)
