### ISSUE TITLE
Techniques layout

### ISSUE THREAD

**Issue by yatil** [w3c/wai-wcag-quickref#17]
<p>The techniques layout has changed. Click on “Show techniques for 1.1.1”. You will find checkboxes for the different types of techniques there (sufficient, advisory, failure).</p>

<p>What do you think of this change?</p>

**Comment by bakkenb** [comment]
Very good update. Very intuitive.

**Comment by vmmiller** [comment]
Good!

**Comment by yatil** [comment]
Andrew Arch in the [survey](https://www.w3.org/2002/09/wbs/35532/EOWG-7July2015/results#xq8):

> this works OK for me, but isn't it really a filter and should be in the sidebar?

**Comment by yatil** [comment]
In the [July 17th meeting](http://www.w3.org/2015/07/17-eo-minutes.html#item09), it was decided to try out having the filter _also_ in the sidebar, so one could generally display only sufficient techniques but for some success criteria also advisory techniques.

**Comment by James-Green** [comment]
I like the flexibility of an overall filter and then allowing exceptions to the rule.
