### ISSUE TITLE
Selecting "Level" filters & Filtered-Out Success Criteria

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-wcag-quickref#170]
I think this is a bug.
[I'm using Window 7 + Chrome, Firefox]

When I load the Quickref page and then use the filters to filter out a conformance level it does show what was removed (at the bottom - and grayed out in-line). But when I add the conformance levels back in by checking the check-box again, the SCs don't go back in. Then the more I play with the check boxes the more it messes up. The only way to get it back working again is to select "clear filters," or reload the page.

![qr conformance bug](https://user-images.githubusercontent.com/11727417/42886410-1e94f54c-8a69-11e8-8003-bf2d4165b943.PNG)

**Comment by yatil** [comment]
D’oh, as they say!

**Comment by yatil** [comment]
Huh, forgot to close this issue that I fixed _a month ago_… :-)
