### ISSUE TITLE
"Clear Filters" button does not clear "WCAG Version

### ISSUE THREAD

**Issue by monkier** [w3c/wai-wcag-quickref#172]
### Description
Given that you can change the WCAG version in the "Filters" tab and the version is listed in the "Selected Filters"  section, I would expect that the "Clear filters" functionality would reset the version filter as well, but it currently does not.

### Steps to reproduce

1. Navigate to the [Quick Reference](https://www.w3.org/WAI/WCAG21/quickref/)
1. Click on the "Filter" tab
1. Change the "WCAG Version" to something other than the initial (in this case, to "WCAG 2.0" or "Only 2.1 Added Success Criteria"
1. Notice the "Selected Filters" text is updated to indicate the current selected version
1. Click the . "Clear filters" button
1. Notice a slight flash in the content, but no change to the filters or the actual content

**Comment by yatil** [comment]
Thanks for reporting, @monkier. 

We’re linking to WCAG 2.0 and 2.1 versions from outside. If people are changing the filters and then reset, they might think that they get back to the version they have been arrived at. I’ll check with my colleagues to see what we want to do.

/cc @slhenry

**Comment by shawna-slh** [comment]
Thanks for the clear comment and steps to reproduce, @monkier.

While the other filters can be cleared/unselected, there is no clear/unselect for the WCAG Version -- one of the 3 options always has to be selected.

**Comment by monkier** [comment]
@slhenry of course one always needs to be selected, I think the UI is a bit confusing and people would expect it to go back to what the original version was when they landed?

A possible solution would be to simply move the currently selected WCAG version copy from the "Selected Filters" text.

Maybe something like:

> WCAG Version selected: WCAG 2.1
> Selected Filters: all success criteria, etc.

Just a thought though.

Thanks!

**Comment by yatil** [comment]
@monkier Thanks for your feedback.

The issue is that we don’t know what the user has landed on, as they come to the page from different URLs which has one of the versions pre-selected. We could save it for the session but then it would be different between sessions, which might also be confusing. I think changing the text somehow might work.
