### ISSUE TITLE
If I "clear filters," I get the same message stating that the filters are blocking the same things.

### ISSUE THREAD

**Issue by MarjaE2** [w3c/wai-wcag-quickref#175]
If I examine this page, and search for its animation standards, I see a message stating "The following success critera are not shown based on the selected tags and/or filters:"

https://www.w3.org/WAI/WCAG21/quickref/?versions=2.0&hidesidebar=true&showtechniques=131%2C133%2C232%2C322%2C323#top

If I click "clear filters" and search again, I get the same message.

**Comment by yatil** [comment]
Hi @MarjaE2, the listed Success Criteria are the WCAG 2.1 SCs that are not in WCAG 2.0. We need to make this more clear :-)
