### ISSUE TITLE
Status notification bar

### ISSUE THREAD

**Issue by yatil** [w3c/wai-wcag-quickref#18]
<p>The status notification bar on the top has changed. Select a tag/level/technologies filter to see the animation and how the text changes.</p>

<p>The text changes are not final yet (there is some polishing to do), but it should give an impression on what to expect here.</p>

**Comment by shawna-slh** [comment]
I have a little niggling discomfort -- but I can't explore and expound on it now. I will try to soon...

**Comment by iadawn** [comment]
I think as [Yellow Fade](https://signalvnoise.com/archives/000558.php) design pattern for highlighting change is much more effective. I can't help but think with the progress bar styling that something is loading or changing over time.

**Comment by bakkenb** [comment]
I like this update. I think it is just a touch too fast. right now the yellow slides across then stays in the whole box for about a half second. I think the animation should take about a second so it is a bit more noticeable.

I also like the yellow fade example that Kevin linked to as another animation option for the "showing" box at the top.

**Comment by sharronrush** [comment]
I like it too, agree with extending the time of the color change. Problem with choosing technologies in FF noted in a new issue.

**Comment by vmmiller** [comment]
Too fast... I'm dizzy.

**Comment by yatil** [comment]
Changed the animation to last a second (https://github.com/w3c/wai-wcag-quickref/blob/gh-pages/_scss/styles.scss#L901). – Actually all changes are instantly thus probably a fading animation is more suitable…
