### ISSUE TITLE
Filter for WCAG 2.1 not working

### ISSUE THREAD

**Issue by Veyfeyken** [w3c/wai-wcag-quickref#183]
Steps to reproduce:

* open filter tab
* choose WCAG 2.1 from dropdown WCAG version
* click button "only" for the tag "visual design"

This doesn't remove any criteria. It does work when WCAG 2.0 is selected.
![quickref-filter-wcag21](https://user-images.githubusercontent.com/870049/54281632-6a2b1800-459a-11e9-8524-d2ead0da9529.png)

**Comment by yatil** [comment]
Hi! Tags for WCAG 2.1 have not been added yet, we are about to release an update. Sorry for the confusion.

**Comment by Veyfeyken** [comment]
No problemo. I submitted the issue in case you hadn't noticed it.

**Comment by yatil** [comment]
And thank you very much for that! :-)

**Comment by yatil** [comment]
On re-reading the issue, this works as is. The selection of the different user groups only filters the available tags, not the actual SCs. (I agree that the UI is not very clear on that and I’ll open an enhancement issue for it.)
