### ISSUE TITLE
horizontal scrolling at 400% zoom

### ISSUE THREAD

**Issue by Veyfeyken** [w3c/wai-wcag-quickref#184]
The quickref doesn't comply to SC 1.4.10 Reflow.

Steps to reproduce:
* set viewport to 1280px width
* zoom to 400% in Chrome

I think it's the following buttons that cause the horizontal scrolling:
"About, How to Use & Preferences"
"Hide in-page navigation and filter options"

![reflow-quickref](https://user-images.githubusercontent.com/870049/55156974-8fec1b80-515b-11e9-9787-303824c6b57d.png)

**Comment by yatil** [comment]
@Veyfeyken Thanks for reporting this bug.
