### ISSUE TITLE
Issue applying filters

### ISSUE THREAD

**Issue by awkawk** [w3c/wai-wcag-quickref#185]
1. Load Quickref: https://www.w3.org/WAI/WCAG21/quickref/
2. Uncheck all but failures: 
* Result: https://www.w3.org/WAI/WCAG21/quickref/?currentsidebar=%23col_customize&techniques=sufficient%2Cadvisory
3. Expand failures for 1.2.1
* Result: https://www.w3.org/WAI/WCAG21/quickref/?currentsidebar=%23col_customize&techniques=sufficient%2Cadvisory
4. Click on Failure F30
5. Hit Back Button
* Result: https://www.w3.org/WAI/WCAG21/quickref/?currentsidebar=%23col_customize&techniques=sufficient%2Cadvisory&showtechniques=121
6. Issue: All techniques are now showing, including the ones that are supposed to be filtered out.
7. If I check “advisory techniques” and uncheck it then the proper state is restored for techniques, including the sufficient ones being properly hidden.

Expected behavior: Filters should remain in place when returning to the page. The addition of  "showtechniques=121" seems to cause the other filters to be ignored.

**Comment by yatil** [comment]
@awkawk Thanks for reporting this bug. Something is wrong with the filtering.
