### ISSUE TITLE
Spelling error on the filtered-Out Criteria

### ISSUE THREAD

**Issue by christosptr** [w3c/wai-wcag-quickref#192]
Issue: Spelling error on the filtered-Out Criteria
URL: https://www.w3.org/WAI/WCAG21/quickref/?currentsidebar=%23col_customize&versions=2.1only&showtechniques=111%2C23#hiddensc
Reproduction steps
1. Use the filter on the quick reference guide.
2. •	Then click on the (What did the filter remove?) link
3. •	In the Filtered-Out Success Criteria Section, the message reads
“The following success critera are not shown based on the selected version, tags, and/or filters:”
The word in error is the 5th word in the sentence “critera” should be criteria

**Comment by yatil** [comment]
@christosptr Thanks, I had the project open coincidently, and we plan an update by the end of the week, so consider this typo as addressed :-D

**Comment by christosptr** [comment]
fantastic!
Great turnaround Thanks @yatil

**Comment by yatil** [comment]
@christosptr You got lucky there, don't get used to it! 😆
