### ISSUE TITLE
Filtering by role not working

### ISSUE THREAD

**Issue by mmeller75** [w3c/wai-wcag-quickref#197]
1. Load Quickref: [](https://www.w3.org/WAI/WCAG21/quickref/)
2. Uncheck the checkboxes for all but 1 role under "Tags" (Developing, Interaction Design, Content Creation, Visual Design).

Result: All Success Criteria are shown, with none filtered out.

Expected behavior: Success Criteria that don't apply to the selected role will be filtered out, leaving only those criteria that apply to the role.

**Comment by yatil** [comment]
Hi @mmeller75. The roles only filter the tags available. This is working as intended. We might look into describing that better in the future.
