### ISSUE TITLE
Typo in SC: 3.2.4 Consistent Identification– Level AA

### ISSUE THREAD

**Issue by sirajrkhan** [w3c/wai-wcag-quickref#198]
Note 1 (Under 3.2.4 Consistent Identification– Level AA) reads:
For instance, you may have **an** graphical

It should read:
For instance, you may have **a** graphical

**Comment by yatil** [comment]
@sirajrkhan Thanks for reporting, I reported it to the source “upstream”: https://github.com/w3c/wcag/issues/925
