### ISSUE TITLE
Hide criteria when filtering

### ISSUE THREAD

**Issue by lchandelier** [w3c/wai-wcag-quickref#199]
Hi,

When we filter by level, it would be more readable if the criteria were hidden in the left column.

**Comment by yatil** [comment]
Hi @lchandelier,

It was explicitly specified by the Working Group that filtered out Success Criteria are kept in the left navigation as it would otherwise be confusing. I’ll keep your issue open for possible future enhancements, maybe the group reconsiders.

**Comment by yatil** [comment]
(Also: #200)

**Comment by iadawn** [comment]
No response from original poster
