### ISSUE TITLE
respect of the tabpanel design pattern

### ISSUE THREAD

**Issue by goetsu** [w3c/wai-wcag-quickref#2]
The tabpanel use too much role="tabpanel" :

```
<div role="tabpanel">
<ul class="nav nav-tabs" role="tablist">...</ul>
<div class="tab-content">
<div id="overview" class="tab-pane overview" role="tabpanel">...</div>
...
</div>
</div>
```

I think it must be changed to something like :

```
<div>
<ul class="nav nav-tabs" role="tablist">...</ul>
<div class="tab-content" role="tabpanel">
<div id="overview" class="tab-pane overview">...</div>
...
</div>
</div>
```

**Comment by yatil** [comment]
Hi, thanks for your feedback and sorry to not get back to you earlier, I think I wasn’t notified of the comments or they got lost over my vacation :-/

The tabpanels are straight from the [bootstrap documentation](http://getbootstrap.com/javascript/#markup) where @patrickhlauke is implementing accessibility, so I guess it might be the right approach. As this is a mere mockup, the code will be refactored and tailored to the application in the end anyway.

**Comment by patrickhlauke** [comment]
I believe this approach, and that from Bootstrap, is the expected/correct one per http://www.w3.org/TR/wai-aria-practices/#tabpanel - each individual panel associated with a tab given its own `role="tabpanel"`, and not just the overall container that has all the various panels.

**Comment by patrickhlauke** [comment]
I believe the confusion here comes from the WAI-ARIA document.

> The content panel uses the role tabpanel.

should really be reworded as

> Each content panel uses the role tabpanel.

(assuming that is indeed the intention of the pattern, which looking at the example provided http://www.oaa-accessibility.org/examplep/tabpanel1/ appears to be the case)

**Comment by patrickhlauke** [comment]
As over in the other issue discussion on bootstrap, where @goetsu crossposted, I realise that he was referring to the first `role="tabpanel"`, and that his proposed fix was then wrong, let me fix this up:

```
<div role="tabpanel">
<ul class="nav nav-tabs" role="tablist">...</ul>
<div class="tab-content">
<div id="overview" class="tab-pane overview" role="tabpanel">...</div>
...
</div>
</div>
```

(note the opening `<div role="tabpanel">`) should be changed to

```
<div>
<ul class="nav nav-tabs" role="tablist">...</ul>
<div class="tab-content">
<div id="overview" class="tab-pane overview" role="tabpanel">...</div>
...
</div>
</div>
```

and yes that is indeed correct. note the second `role="tabpanel"` (which is all I saw when skimming over the OP) is however correct and needs to remain.

**Comment by yatil** [comment]
Thanks for the clarifications, @patrickhlauke!

**Comment by goetsu** [comment]
yes sorry for that. 

For the second tabpanel I was confused by the tablist inside it. 

```
<div class="tab-content">
<div id="overview" class="tab-pane active overview" role="tabpanel">
<ul class="nav nav-pills nav-stacked" role="tablist">
```

**Comment by patrickhlauke** [comment]
> For the second tabpanel I was confused by the tablist inside it.

Yup, that's also wrong in Bootstrap's docs. Both those instances will be removed in the next release, as per https://github.com/twbs/bootstrap/pull/16167 - thanks for spotting those!
