### ISSUE TITLE
Update Techniques 

### ISSUE THREAD

**Issue by yatil** [w3c/wai-wcag-quickref#201]
To address https://github.com/w3c/wcag/issues/927

**Comment by mattsheppard** [comment]
Hi - Is there anything I can do to assist this one in progressing?

As I said on #204 I'd be willing to make a PR for that aspect at least. Maybe I'm misunderstanding and that file wcag21.json file is generated by some other process? If so, I might also be able to take a look at that generation process if someone can point me in the right initial direction.

**Comment by yatil** [comment]
@mattsheppard Thanks for your offer to help. The wcag21.json file is generated from the WCAG source code at https://github.com/w3c/wcag. It is an XML/XSLT process, but I personally don’t know what is needed to make it work. @michael-n-cooper is the person who knows the build scripts, maybe he wants to chime in…

**Comment by jake-abma** [comment]
can we can a fix for this one? thx!

**Comment by iadawn** [comment]
Closing this as I am working on addressing the known required updates. Additionally we are also looking at the build process which should allow for improvements and consistency in updating the JSON
