### ISSUE TITLE
[low, later] Delete Flash and Silverlight from Filters (under "Technologies")

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-wcag-quickref#208]
From the Filter, under "Technologies", delete Flash.
Probably also Silverlight.

Timing: When removed from Techniques.

Rationale: https://github.com/w3c/wcag/issues/1140

**Comment by yatil** [comment]
Update JSON, then remove the last two entries in this file: https://github.com/w3c/wai-wcag-quickref/blob/gh-pages/_filters/4-technologies.md

**Comment by shawna-slh** [comment]
Thanks, Eric!
