### ISSUE TITLE
Typo: refow and reflow

### ISSUE THREAD

**Issue by mitchellevan** [w3c/wai-wcag-quickref#210]
Steps to reproduce:

1. Go to https://www.w3.org/WAI/WCAG21/quickref/
2. Activate "Filter"
3. Activate "Show All Tags"

Expected result:

It should include a tag called "Reflow"

Actual result:

It includes a tag "Reflow" and also a tag "Refow" without the L.

**Comment by yatil** [comment]
Thanks @mitchellevan, I saw it and I made the quick change to the tagging file, see #214.

**Comment by yatil** [comment]
It’s now almost three years after the issue has been reported, and a fix has been merged, and the typo is still live on the website. 

![Screenshot showing the “refow” tag next to the “reflow” tag.](https://github.com/w3c/wai-wcag-quickref/assets/58862/c59ee73f-1497-4190-8251-e7b0c6e9eb32)
