### ISSUE TITLE
Would like to be able to easily go back to the Table of Contents

### ISSUE THREAD

**Issue by DavidMacDonald** [w3c/wai-wcag-quickref#22]
going down the TOC select an item throws focus to the correct section... but back space doesn't return me to where I was... not sure why...

**Comment by yatil** [comment]
Hi @DavidMacDonald, is that really the intended behavior? I have never seen the backspace button work this way as far as I can remember. 

Feel free to prove me wrong :-)

**Comment by bakkenb** [comment]
The backspace worked for me in Chrome when I selected links in the TOC to get to specific SCs. When I backspaced it pulled me back out to previous view. I did not test this in IE or FF.

**Comment by yatil** [comment]
Clarification in the WCAG meeting 2015-09-22: The most important thing is that you can jump quickly back to the TOC in one form or another.

**Comment by yatil** [comment]
This should now work (better) as I am now changing the fragment/hash portion of the URL when moving to a SC.
