### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by mgifford** [w3c/wai-wcag-quickref#223]
What license is this released under?

Would love a LICENSE.md file to make that clear.

**Comment by shawna-slh** [comment]
Here you go: https://github.com/w3c/wai-wcag-quickref/blob/gh-pages/LICENSE

Reminder that all these are under W3C license. https://www.w3.org/Consortium/Legal/2015/copyright-software-and-document
That's linked to from the footer (though from "Usage policies apply.").

General info is in [Using WAI Material: Permission to Use with Attribution ](https://www.w3.org/WAI/about/using-wai-material/)
