### ISSUE TITLE
When will the Silverlight Techniques be removed?

### ISSUE THREAD

**Issue by ollie-iterators** [w3c/wai-wcag-quickref#226]
I've noticed that the Silverlight resources are still on the document, despite the Silverlight plugin being deprecated on October 12, 2021, and the Silverlight plugin having a small number of sites using it.

https://w3techs.com/technologies/details/cp-silverlight

I think it might be best for those areas to be archived and moved from the How to Meet WCAG 2.0 document.

**Comment by fstrr** [comment]
[Silverlight techniques will be removed from WCAG 2.1 onwards soon](https://github.com/w3c/wcag/pull/2449).
