### ISSUE TITLE
Typo on 1.1.4 Resize text

### ISSUE THREAD

**Issue by colinjamesfirth** [w3c/wai-wcag-quickref#234]
The heading is in sentence case 'Resize text', when all the others are title case (i.e. Images of Text, Visual Presentation).

For consistency, the heading should be title case: 'Resize Text.

**Comment by SamSverko** [comment]
Going off this repo's README, it looks like the data for the QuickRef site comes from another repo:

> The data is saved as [wcag21.json](https://github.com/w3c/wai-wcag-quickref/blob/gh-pages/_data/wcag21.json) in the _data directory. Due to the complexity of the WCAG standard, the JSON file format is also quite complex. **The data is exported from the [WCAG source code](https://github.com/w3c/wcag) and handed over to this repository.**

I dug into the [wc3/wcag](https://github.com/w3c/wcag) codebase and found that this editorial change was made on June 28, 2021 ([commit](https://github.com/w3c/wcag/commit/dfc22fe42bf8211cca764f07bdaa02d7dd6789a6)).

One would think this means the public [WCAG document](https://w3c.github.io/wcag/guidelines/#resize-text) would be updated, but the process seems to be much more complicated. The "[Status of this Document](https://w3c.github.io/wcag/guidelines/#sotd)" section of WCAG states:

> This draft incorporates [errata](http://www.w3.org/WAI/WCAG21/errata/) and are described in the [change log](https://w3c.github.io/wcag/guidelines/#changelog). At some point these changes might be incorporated into a [Edited or Amended Recommendation](https://www.w3.org/2018/Process-20180201/#revised-rec).

So it looks like an editorial change such as this one - which has already been accepted into the codebase - needs additional support by WCAG working groups to actually get implemented into the public WCAG document. I'm not part of any of those groups, so I can't provide much more info on this.

**Comment by yatil** [comment]
Correct, this is the official way to write the name of the Success Criterion in WCAG 2.1. See: https://www.w3.org/TR/WCAG21/#resize-text

It’s going to change in WCAG 2.2:
https://www.w3.org/TR/WCAG22/#resize-text

It’s unclear (to me) how this quickref is going to be updated for 2.2.

**Comment by iadawn** [comment]
This has been addressed for 2.2 release
