### ISSUE TITLE
DOCUMENT NOT FOUND - FLASH5: Combining adjacent image and text buttons for the same resource

### ISSUE THREAD

**Issue by IrinaNj** [w3c/wai-wcag-quickref#239]
https://www.w3.org/WAI/WCAG21/quickref/?currentsidebar=%23col_overview

1.1.1 Non-text Content Level A
Situation A: If a short description can serve the same purpose and present the same information as the non-text content:
FLASH5: Combining adjacent image and text buttons for the same resource - document is missing

**Comment by yatil** [comment]
Duplicate to 
- https://github.com/w3c/wai-wcag-quickref/issues/208

**Comment by iadawn** [comment]
Flash and Silverlight Techniques seem to have been removed
