### ISSUE TITLE
Table of contents area auto-updates when you scroll.

### ISSUE THREAD

**Issue by mraccess77** [w3c/wai-wcag-quickref#24]
Dynamic changes occur in the TOC (e.g. SC 2.2.2) when you scroll.  These changes can't be turned off except without hiding the TOC.  It would be great if there was an option to suppress this distraction without having to hide the TOC.

**Comment by yatil** [comment]
Thanks for the comment, I will consider this.

**Comment by bakkenb** [comment]
If this is option is implemented, I would suggest the default is to have the dynamic TOC change on when scrolling and the user would have to activate a setting to turn it off.

**Comment by yatil** [comment]
The Success criteria are now shown always which reduces the animation. The highlighting is still there to give users orientation.
