### ISSUE TITLE
Redirect WCAG 2.1 Quickref to WCAG 2.2 Quickref with WCAG 2.1 selected by default

### ISSUE THREAD

**Issue by yatil** [w3c/wai-wcag-quickref#246]
Redirect 

`https://www.w3.org/WAI/WCAG21/quickref/`

To

`https://www.w3.org/WAI/WCAG22/quickref/?versions=2.1`

Basically, add `versions` string for WCAG 2.1, if none is provided. If a versions string is provided, do not change URL parameters.

This allows updating in one place and backwards compatibility.

**Comment by shawna-slh** [comment]
and also

```https://www.w3.org/WAI/WCAG20/quickref/```

to 

```https://www.w3.org/WAI/WCAG22/quickref/?versions=2.0```

**Comment by shawna-slh** [comment]
Done.

thanks @yatil!
