### ISSUE TITLE
How to Meet WCAG (Quick Reference) Page not sharing filtered reference page URL only default page URL

### ISSUE THREAD

**Issue by douglasburns28** [w3c/wai-wcag-quickref#253]
![WCAG Filtered URL](https://github.com/w3c/wai-wcag-quickref/assets/153209480/c98e6af4-b1d3-4b79-82d7-3951f4f8424e)
When I go to the How to Meet WCAG (Quick Reference) page
https://www.w3.org/WAI/WCAG22/quickref/?versions=2.1&currentsidebar=%23col_customize&levels=aaa#top
And filter the page to only show A & AA (for WCAG 2.1)
Then attemp to share the URL, wha tis copied when sharing is the default URL Page (without the restriction of A & AA Filtering)
 Can someone help me get a URL that shows WCAG 2.1 Level A & AA?

**Comment by iadawn** [comment]
Hi, the URL that you shared seems to do what you are looking for. Not sure what you are seeing when you visit that URL
