### ISSUE TITLE
Techniques no longer part of WCAG but still accessible via Quickref

### ISSUE THREAD

**Issue by giacomo-petri** [w3c/wai-wcag-quickref#255]
Hi,

Certain techniques, like H35 ([H35: Providing text alternatives on applet elements](https://www.w3.org/WAI/WCAG22/Techniques/html/H35.html)), have been eliminated from WCAG 2.2 but are still available on the Quick Reference page.

Updating the content to align with WCAG 2.2 would be advisable.

Edit: relates to [3779](https://github.com/w3c/wcag/pull/3779)

**Comment by shawna-slh** [comment]
Hi @giacomo-petri Thank you for pointing out this example.

@iadawn Assuming we're going to keep editing this JSON by hand until we get the new generated one, could you get some AG folks to provide PRs for the updates?

**Comment by iadawn** [comment]
This doesn't really fall with AG remit to maintain the supporting resources
