### ISSUE TITLE
The 4.1 section is messed up.

### ISSUE THREAD

**Issue by yan-ilumino** [w3c/wai-wcag-quickref#261]
On the quick reference guide, the [4.1.1 Parsing (Obsolete and removed)](https://www.w3.org/WAI/WCAG22/Understanding/parsing) success criteria have been entirely removed (instead of leaving it as obsolete and removed), and its has now moved up 4.1.2 to 4.1.1 and 4.1.3 to 4.1.2.

Quick reference view:
![2024-08-05_12-53-13](https://github.com/user-attachments/assets/7c8bdcd1-484d-4cb1-8879-52db56664c56)
Reference: https://www.w3.org/WAI/WCAG22/quickref/#compatible

The Understanding WCAG 2.2 view:
![2024-08-05_13-03-15](https://github.com/user-attachments/assets/bbb9fa89-30fe-4304-803e-a19d4efcf495)
Reference: https://www.w3.org/WAI/WCAG22/Understanding/compatible

So either it's a sign of what's coming and was meant to be like that, or it was an issue with the latest update. Updated 02 Aug 2024. Version 3.5.1.

**Comment by iadawn** [comment]
Hmm... that wasn't intended. The renumbering rather than the removal. Will look into it and fix.

**Comment by iadawn** [comment]
Fixed. 4.1.1 should not appear if WCAG 2.2 filtering is selected. The success criterion was removed from 2.2. It does appear in 2.0 and 2.1 with appropriate notes.

**Comment by yan-ilumino** [comment]
Thx @iadawn!
