### ISSUE TITLE
Top bar styling

### ISSUE THREAD

**Issue by yatil** [w3c/wai-wcag-quickref#31]
@melodyma via survey:

> There's not enough distinction between the sticky top bar of "Showing success criteria..." and the content body. "Share this view" and "Clear all filters" formatting is funky in smaller viewport.

I agree that there is some work to do, especially with a lot of text in the sticky status bar. I don’t know what to do with the sticky bar to make more of an distinction without giving away too much screen real estate here.

**Comment by melodyma** [comment]
Darkening the background of the top bar or providing more prominent bottom border. It just needs to be visually distinct from the rest of the body content.

**Comment by yatil** [comment]
In addition the filter bar is now in a yellow color when a tag is selected.
