### ISSUE TITLE
Table of contents doesn't use full page height

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-wcag-quickref#32]
Firefox 40.0.3, iOS 10.10.4

<img width="224" alt="left navigation does not expand to full height
" src="https://cloud.githubusercontent.com/assets/2444840/9979972/9482c4d2-5f7e-11e5-8e8a-2868355b9f3b.png">

**Comment by yatil** [comment]
I have tracked this one down. It seems to happen when the window gets resized. The resize event _should_ fire, yet it does not.

**Comment by yatil** [comment]
This should now be fixed.
