### ISSUE TITLE
Put Filter Below  Content menu

### ISSUE THREAD

**Issue by GreggVan** [w3c/wai-wcag-quickref#37]
Some people will not understand the title "filter"
Some will not know that very usable things are there (sounds technical)
Having tabs there complicates the interface cognitively and for non sighted users

Since the content menu is short -  Position the Filter menu below it. That way both are always visible, discoverable, and usable.  (and never disappear or are hidden)

**Comment by GreggVan** [comment]
I just found another reason to do this.  I was using it and couldnt figure out why some of the provisions were greyed out.    finally I looked in the filter tab and saw that I had selected a tab.  I cleared it and I could see them all again.       having them always be visible would have caused me to figure this out faster.   (and some people to figure it out at all)

**Comment by yatil** [comment]
Hi Gregg,

we conducted user feedback sessions on the general layout a while back and this was the best compromise. Please also note that the content menu is short in the beginning, it gets larger when the user scrolls the view as the success criteria are then visible as well.

Also note that we have a status bar on the top that says what is shown and what is not shown, including a possibility to clear all settings.

Eric

**Comment by GreggVan** [comment]
Ah - I see what you mean.  I didn't notice that before.  Yes -that makes my idea not work well. 

So you can consider this suggestion as closed.

**Comment by yatil** [comment]
Thanks Gregg!
