### ISSUE TITLE
TOC doesn't show Success Criteria

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-wcag-quickref#40]
With 'Dynamic highlight position in document' unchecked.

If I click on a Guideline, e.g. 1.2 Time-based media, I would expect that this would reveal the SC in the TOC.

When dynamic highlight is checked, scrolling will reveal SC as will clicking on a link (although see #33).

Note that, if 'Dynamic highlight position in document' is checked, then any previously visible SC stay visible, regardless of what is clicked, or scrolling behaviour.

**Comment by yatil** [comment]
I have added the success criteria and highlighting (as discussed with @nitedog this morning), but there are some issues: 
- The SCs are very long, so the sidebar is very long, too.
- The highlighting works but doesn’t scroll the sidebar, so it might be that items are highlighted but invisible. As I think that we don’t want to automatically scroll the sidebar, that is probably something we need to live with…

**Note:** The display of items in the overview column is not (yet) reflecting the visible Principles/Guidelines/Success Criteria.

**Comment by iadawn** [comment]
👍🏻
