### ISSUE TITLE
Value of referring users to the right

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-wcag-quickref#41]
In the filter panel there is the note:

> Changes in this panel are reflected on the right

I wonder if there is any realisitc value to this, as it is easily lost. Also, I wonder if this is not falling foul of [F14](http://www.w3.org/TR/WCAG20-TECHS/F14.html).

**Comment by yatil** [comment]
Yeah, it kind of is, but it is just an approach to demonstrating a possible solution to #36. I personally don’t think it is really essential information but more like a reminder. Will refine that further.
