### ISSUE TITLE
Disabled techniques buttons are visually prominent

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-wcag-quickref#43]
<img width="499" alt="disabled_button_visibility" src="https://cloud.githubusercontent.com/assets/2444840/10336288/8b497554-6cef-11e5-877e-9a43e3c5beb5.png">

The visibility of the disabled buttons is significantly prominent. The level of prominence draws more attention to them and suggests 'use me', which is not possible.

Two suggestions:
- Tone them down significantly; not sure why the whole label is highlighted
- Remove them; not sure what value it serves to keep them there if they can't be used

**Comment by yatil** [comment]
The value is that the display is consistent, sufficient is always first, advisory always second and failures always 3rd.
