### ISSUE TITLE
Show Sidebar Button Jumps to Right, Could be on left?

### ISSUE THREAD

**Issue by James-Green** [w3c/wai-wcag-quickref#46]
The show sidebar button jumps to the right a bit when you start to scroll down on FF 31 on a Mac 10.9.5.  Not sure if that was by design or not, but I might suggest placing the button on the left, maybe in a vertical bar like many applications do.  That would keep it off the top of the screen and be less distracting as the content behind it scrolls by...
![screen shot 2015-10-12 at 9 21 29 pm](https://cloud.githubusercontent.com/assets/13589074/10444053/5e977d12-7127-11e5-9600-ec7dd12d7ee6.png)

**Comment by yatil** [comment]
This should be fixed with the commit ab19b71e0549ba4feea8c4fac52d0822c4693cda.
