### ISSUE TITLE
Share Button Functionality

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-wcag-quickref#48]
There is an issue, within and across browsers, that I am noticing about the Share button and the way it functions when copying a link. I will try to describe what is happening to me.

Browser Versions that I am using on a windows 7 machine:
- Chrome: Version 45.0.2454.101 m
- Firefox: Version 40.0
- IE: 10.0.9200.17492

1) When I copy a "Link to this section" URL and use it in a new window, the Success Criteria number and name are covered at the top by the tag/filters showing and hiding box that is anchored there as a result of not being at the top of the page. This happened in all three browsers.

2) In reference to the use case above, when I pasted the link into a new window, the first time it just opened the quick-ref as a new page and did not jump to the anchor from the link. Then when I pasted it in the same window a second time, it would jump to the appropriate anchor. This happened in Chrome and FireFox browsers, but with different manifestations. For example, when I did this in Firefox and copied the link for section 2.4.3 and pasted it in a new FF window, it jumped to the anchor for 3.1.3. Further more, when I did this within IE, instead of going to the quick-ref anchor, it did a Bing search using the copied URL. When I copied the "Link for this section" URL from IE and tried to use it in FF, it did the same thing, searched the web using the URL. However, when I did this from IE to Chrome, I got a "page not found" error.

**Comment by yatil** [comment]
This should now work much better (but not perfect, unfortunately). Will further investigate.
