### ISSUE TITLE
There are no horizontal scrollbars at lower resolutions

### ISSUE THREAD

**Issue by mraccess77** [w3c/wai-wcag-quickref#58]
At lower resolutions such as 800x600 there are no horizontal scrollbars and the view does not go into responsive mode and some controls are unavailable.

**Comment by kwahlbin** [comment]
I agree.  Also on the desktop, if you zoom the content with the About section is expanded you can no longer information below the About section.

**Comment by yatil** [comment]
Thanks for reporting this – there should be no horizontal scrollbars needed as the content should fit into the view. I will have another look and see how to adapt the media queries. (Related to #57)

**Comment by yatil** [comment]
Hi! This is my view at 800x600 (w/ the slimmer header). There are no horizontal scroll bars. Can you please indicate which browser you’re using?

![](https://cloud.githubusercontent.com/assets/58862/11188025/3796e14e-8c89-11e5-8524-8de48b1e20b1.png)

**Comment by mraccess77** [comment]
Yes, that looks about the way it appears to me.  Working solely in that right hand pane is very constricted.  I have tried in Chrome and IE 11 both on Windows.

Jonathan

**Comment by yatil** [comment]
@mraccess77 I wonder if there is anything I can do here. I will try to have the header scrolling out of the way somehow, but I can’t promise anything, I’m afraid.
