### ISSUE TITLE
Button and link text of nav elements not meaningful

### ISSUE THREAD

**Issue by spanchang** [w3c/wai-wcag-quickref#60]
Review of the Quickref Prototype  (mockup) at
http://w3c.github.io/wai-wcag-quickref/
On Windows, 3 elements are exposed to NVDA and JAWS in the main navigation section:
A "hide button expanded", ", "a Content collapsed" linjk and "a Filter expanded" link.
The button text or anchor text   for these elements are not very meaningful.

The button (id=hidesidebars ) is exposed as "hide button expanded" 
Not clear what it is  ... I know it relates to the nav menu.
And, likewise, when it is collapsed, the button is replaced with another (id=showsidebars) which is announced as "Show Sidebar collapsed". Why show and collapsed together?
Consider  setting aria-label on these elements to clearly expose their purpose.  
Interestingly with VO on iOS, the "content link" appears quite meaningful:  
"Content link navigation landmark collapsed".
On iOS, there are only two elements: the Content link and Filter link expanded. The latter does not appear to do anything.

**Comment by yatil** [comment]
Hi @spanchang – It looks like this is somehow mixed up ARIA metaphors:

“Hide (sidebar), expanded” means that the sidebar is expanded and you have the possibility to hide it. Obviously the additional information of ARIA is more confusing than helping. I will use `aria-label` to have both buttons say “Toggle Sidebar, expanded” or “Toggle Sidebar, collapsed”. That should avoid the confusion.

I will also see if I can change the ARIA on the toggles for the Content and Filter buttons to something more sensible. That should then also address the VO issues you’re experiencing.
