### ISSUE TITLE
Instruction text in tab panel fails SC 1.3.3

### ISSUE THREAD

**Issue by spanchang** [w3c/wai-wcag-quickref#61]
Review of the Quickref Prototype  (mockup) at
http://w3c.github.io/wai-wcag-quickref/

The instruction at the start of the tab panel in the nav section "Changes in this panel are reflected on the right" fails SC 1.3.3.

**Comment by yatil** [comment]
Thanks for your feedback. We got similar feedback in #72 and I’m rolling those comments into one.
