### ISSUE TITLE
Enhancement, add colour to show scroll position

### ISSUE THREAD

**Issue by DavidMacDonald** [w3c/wai-wcag-quickref#63]
Currently as the user scrolls down the right side, the left table of contents highlights the Guideline and Success Criterion with boxes. I suggest add colour to those boxes. Perhaps going to reverse contrast for the highlighted Success Criteria (White text on Dark blue fill in the box around the SC), and perhaps a pale yellow fill for the box around the Guidleline. So as the user scrolls the Success criteria on the right, the corresponding success criteria on the  left will pop by going to reverse contrast.

On the left menu of my "rather old" website, I've done that and it has worked well http://davidmacd.com/ 
Hover over the left menu

**Comment by yatil** [comment]
Thanks for the idea. This was addressed in 8eb267f39d6a8305e1fa14e2a3ae8b2406f95f08.
