### ISSUE TITLE
Content section Highlight & Focus on the page are not the same

### ISSUE THREAD

**Issue by yatil** [w3c/wai-wcag-quickref#66]
Reported by @HerinHentry in w3c/wai-quick-start#302

> Issue : On Selecting a content menu item, the page loads correctly. But, the content section highlights the previous link. See screenshot below.
> Sample url : http://w3c.github.io/wai-wcag-quickref/#time-limits
> ![](https://cloud.githubusercontent.com/assets/15111528/11241604/325964e0-8e50-11e5-8321-28a463da4aed.png)

_This issue had been submitted on the wrong repository as a result of an error in the Public Review email._

**Comment by mitchellevan** [comment]
After some experimentation, I figured out that this highlight is trying to match the scroll position of the main body content. I don't see the value of it, and it contributes to the clutter of too many typographic styles. I suggest simply removing this highlight behavior.

**Comment by yatil** [comment]
Hi @mitchellevan,
we did user testing a few months ago and the addition of this scrolling behavior was requested and welcome and provided much needed orientation for users. The highlight coloring was refined in a process including WCAG WG and EOWG. I personally don’t think that outright removing it will benefit orientation in the document but will bring it as a discussion item to the groups.

Eric

**Comment by mitchellevan** [comment]
User testing wins. <smile>
