### ISSUE TITLE
Selected and Unselected/deselected tags not clear in filters

### ISSUE THREAD

**Issue by HerinHentry** [w3c/wai-wcag-quickref#67]
Please see screenshot below. The deselected option is still showing in a different colour compared to the others. Is this necessary?

![image](https://cloud.githubusercontent.com/assets/15111528/11259557/937282b4-8eb6-11e5-8482-90557542b50f.png)

**Comment by yatil** [comment]
Hi @HerinHentry,

the light background item has the (keyboard) focus, the dark background item is selected. I will make that visually more clear.

Eric
