### ISSUE TITLE
Principle _ Guideline _ Success Criteria _ Techniques (Hierarchy could be made clear)

### ISSUE THREAD

**Issue by HerinHentry** [w3c/wai-wcag-quickref#69]
Users are consistently across the hierarchy (Principle _ Guideline _ Success Criteria _ Techniques).

http://w3c.github.io/wai-wcag-quickref/ refers to 
Principle 1 _ Perceivable to Principle 4_ Robust.

We do not refer to the Guidelines and Success Criteria any where using these words (as highlight) other than few references here and there.

We use the word Techniques as expected. I think this is very important to keep that hierarchy in this quick reference too. Even in the filters, we have not included filtering by success criteria.

**Comment by yatil** [comment]
Hi @HerinHentry,
thanks for your feedback… Is your impression that we are not using the word “Principle” or the name of the principles “Perceivable, Operable, Understandable, Robust” (or both?) <q>any where using these words (as highlight) other than few references here and there</q>?

I do not see where the tool is not maintaining the hierarchy, can you please explain that a bit more?

Thanks,
Eric

**Comment by HerinHentry** [comment]
Hi @yatil, Thanks for getting back. Sorry the summary was not clear.
For a novice user, For example, 1.1.1 may need bit more clarity on whether it's a Guideline or a Success Criteria.

![image](https://cloud.githubusercontent.com/assets/15111528/11270595/65d34f7e-8f14-11e5-9b7e-ee7d86b5aea2.png)

**Comment by yatil** [comment]
Ah, thanks @HerinHentry – Would it be sufficient to have “Guideline 1.1” in the guideline description, like it is done in the current “How to Meet” document: http://www.w3.org/WAI/WCAG20/quickref/#text-equiv

I think this also relates to #70.

**Comment by HerinHentry** [comment]
@yatil Yes. I think that will be sufficient. Thanks and Regards, Herin

**Comment by davidberman** [comment]
"Success criterion" should be singular in this case. "Criteria" is plural.

**Comment by yatil** [comment]
Hi @davidberman: As noted above (but not very clearly), we don’t plan to add  the phrase “success criterion” to every success criterion as that would add unnecessary clutter to the page. The success criteria are easy to distinguish now that we have added the “Guideline” prefix to every guideline.

**Comment by davidberman** [comment]
Understood. So I'm saying that should the consensus end up with the phrase being included, then we must use the proper singular/plural. All good!
