### ISSUE TITLE
Understanding Success Criterion Button _ Name change suggestion

### ISSUE THREAD

**Issue by HerinHentry** [w3c/wai-wcag-quickref#70]
Understanding 1.4.1 or any other similar button can be labelled as "Understanding Guideline 1.4.1".

![image](https://cloud.githubusercontent.com/assets/15111528/11260095/0e7297a6-8ebc-11e5-89e7-f6d9eca27437.png)

**Comment by davidberman** [comment]
I think it was better off as "Understanding 1.4.1", but I'm fine with the new approach. I feel this way because "SC" is just as jargony as having nothing.

**Comment by shawna-slh** [comment]
From survey: "Suggested solution: Add <abbr title="Success Criterion">SC</abbr> to the button to make clear that the button is related to the success criterion."

afaik, most people do not get the abbr title.

I think it adds unnecessary cognitive load for people who are not familiar with the abbreviation. Do we use it elsewhere?

I vote for leaving it off. [medium-high]

**Comment by iadawn** [comment]
The current addition includes an `<abbr>` to every instance of this. Will that result in a degraded experirence for some AT users?

I ask only as I think I recall such concerns being raised regarding a similar thing in tips.

**Comment by yatil** [comment]
/me adds this to the agenda for the meeting.

**Comment by bakkenb** [comment]
I am in the opinion of not using "SC" as well. Some will not know what that means. Also, currently we have "Principle" and "Guideline" words used in the main content frame but chose not to include the acronym "SC" or words "Success Criteria". Therefore, I do not believe it is needed in the button. 

Example: When you are on 1.3.2, the title is "1.3.2 Meaningful Sequence - Level A," so the button should just be labeled "Understanding 1.3.2."

**Comment by davidberman** [comment]
Agreed!

On 10 December 2015 at 20:42, Brent Bakken notifications@github.com wrote:

> I am in the opinion of not using "SC" as well. Some will not know what
> that means. Also, currently we have "Principle" and "Guideline" words used
> in the main content frame but chose not to include the acronym "SC" or
> words "Success Criteria". Therefore, I do not believe it is needed in the
> button.
> 
> Example: When you are on 1.3.2, the title is "1.3.2 Meaningful Sequence -
> Level A," so the button should just be labeled "Understanding 1.3.2."
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/w3c/wai-wcag-quickref/issues/70#issuecomment-163807252
> .

## 

David Berman, RGD, FGDC
David Berman Communications | berman@davidberman.com | @davidberman | blog
http://www.designedgecanada.com/author/david-berman
+1-613-728-6777 | 340 Selby Avenue, Ottawa K2A 3X6

High Level Advisor, United Nations | GDC ethics chair | Ico-D

## Sustainability chair | Carleton University Access Network chair

_Accessibility courses:_ Ottawa | Dublin | Toronto | Washington
_Upcoming:_ Toronto | Mexico City | North Bay | Cyprus | Bahrain
Watch David on CBS
http://www.wtoc.com/story/17588481/scad-plans-revitalization | Do Good
book news:  http://www.dogoodbook.com/ http://www.dogoodbook.com/"Don't
just do good design ... do good!"

This message may contain proprietary information. Unauthorized
disclosure/copying/distribution of contents prohibited.
