### ISSUE TITLE
Focus of what did the filter remove extends below the filtered success criteria section

### ISSUE THREAD

**Issue by HerinHentry** [w3c/wai-wcag-quickref#73]
Please see the screenshot below from Chrome Version 46. The focus marked in Blue extends below to the Contribute section.

![image](https://cloud.githubusercontent.com/assets/15111528/11317986/20b3fb82-9095-11e5-8274-b4cb2a4bb273.png)

**Comment by yatil** [comment]
Hi, that's an unfortunate Chrome bug related to multi column layouts. I’m afraid there is little I can do here.
