### ISSUE TITLE
Add short example to success criteria

### ISSUE THREAD

**Issue by yatil** [w3c/wai-wcag-quickref#75]
[Mail Feedback](https://lists.w3.org/Archives/Public/wai-eo-editors/2015Nov/0008.html)

> I've long though it would be tremendously valuable to have a short concrete example with each criterion so that the impact is clear. For example, for 1.1, the example might be, "Technology used by blind individuals cannot interpret graphics. An appropriate text equivalent will convey any important information that the graphic contains."

**Comment by shawna-slh** [comment]
survey results: https://www.w3.org/2002/09/wbs/35532/EOWG18Dec2015/results#xqr4

**Comment by yatil** [comment]
As per the survey result, other resources are probably better fits for such examples.
