### ISSUE TITLE
Add “Note: Other techniques may also be sufficient if they meet the success criterion.” to every sufficient techniques box.

### ISSUE THREAD

**Issue by yatil** [w3c/wai-wcag-quickref#76]
[Mail feedback](https://lists.w3.org/Archives/Public/wai-eo-editors/2015Nov/0006.html)

> I'm missing the notes "Other techniques may also be sufficient if they meet
> the success criterion" which were placed some years ago before every list of
> Sufficient Techniques. 
> 
> These notes were added some years ago because of misunderstandings about the
> character of Sufficient Techniques and to inform the public (especially
> evaluators, consultants and participants in legal specifications) on the
> earliest possible point in WCAG 2.0  that Sufficient Techniques are just
> options for meeting an SC. 
> 
> Please add this very important note before every list of Sufficient
> Techniques into the next draft to make very clear that Sufficient Techniques
> are still options, that the character of techniques did not changed and
> especially for avoiding further misunderstandings.

**Comment by yatil** [comment]
From @slhenry in commit b33c710:

---

I think we should consider this, probably with WCAG WG. Maybe we don't need to have that sentence before every list?

This is related to the important info from the existing intro, that is missing in this draft:
"
About the Techniques
For important information about the techniques, please see the <a href="http://www.w3.org/TR/2014/NOTE-UNDERSTANDING-WCAG20-20140916/understanding-techniques.html#understanding-techniques">Understanding Techniques for WCAG Success Criteria</a> section of Understanding WCAG 2.0.
Note: The basis for determining conformance to WCAG 2.0 is the success criteria, not the techniques. (The success criteria have 3-level numbering (0.0.0) and in this page they are followed by a link "Understanding Success Criterion".) All techniques are informative; that means they are not required. There may be other techniques besides the ones listed here.
"

What is the least cluttering, yet clear, way to get this message across?

Straw proposal 1:
* Add to the About section:  All techniques are informative; they are not required. <strong>Please read important information in the <a href=" http://www.w3.org/TR/UNDERSTANDING-WCAG20/understanding-techniques.html#understanding-techniques ">Understanding Techniques for WCAG Success Criteria</a></strong> section of Understanding WCAG 2.0.
* Not include "Note: Other techniques may also be sufficient if they meet the success criterion." with every listing.

Con: If people don't open the About section, they won't see it.
Pro: Cuts clutter of the note all over.

Straw proposal 2:
* Before all techniques (under or after "Hide techniques and…" button): Put <blockquote>"All techniques are informative; they are not required. See <a href="http://www.w3.org/TR/UNDERSTANDING-WCAG20/understanding-techniques.html#understanding-techniques">Understanding Techniques for WCAG Success Criteria</a>.</blockquote>
Pro: It's all over so can't miss it. It links to the important info.
Con: It's all over so cluttering.
Possible con: It doesn't specifically say sufficient.

Straw proposal 2a:
* Nothing in the About section.

Straw proposal 2b:
* Add to the About section:  All techniques are informative; they are not required. <strong>Please read important information in the <a href="http://www.w3.org/TR/UNDERSTANDING-WCAG20/understanding-techniques.html#understanding-techniques ">Understanding Techniques for WCAG Success Criteria</a></strong> section of Understanding WCAG 2.0.

**Comment by shawna-slh** [comment]
I think we should consider this, probably with WCAG WG. Maybe we don't need to have that sentence before every list?

This is related to the important info from the existing intro, that is missing in this draft:

<blockquote>
About the Techniques
For important information about the techniques, please see the <a href="http://www.w3.org/TR/2014/NOTE-UNDERSTANDING-WCAG20-20140916/understanding-techniques.html#understanding-techniques">Understanding Techniques for WCAG Success Criteria</a> section of Understanding WCAG 2.0.
Note: The basis for determining conformance to WCAG 2.0 is the success criteria, not the techniques. (The success criteria have 3-level numbering (0.0.0) and in this page they are followed by a link "Understanding Success Criterion".) All techniques are informative; that means they are not required. There may be other techniques besides the ones listed here.
</blockquote>

What is the least cluttering, yet clear, way to get this message across?

Straw proposal 1:
- Add to the About section: <blockquote>All techniques are informative; they are not required. <strong>Please read important information in the <a href="http://www.w3.org/TR/UNDERSTANDING-WCAG20/understanding-techniques.html#understanding-techniques ">Understanding Techniques for WCAG Success Criteria</a></strong> section of Understanding WCAG 2.0.</blockquote>
- Not include "Note: Other techniques may also be sufficient if they meet the success criterion." with every listing.

Con: If people don't open the About section, they won't see it.
Pro: Cuts clutter of the note all over.

Straw proposal 2:
- Before all techniques (under or after "Hide techniques and…" button): Put <blockquote>"All techniques are informative; they are not required. See <a href="http://www.w3.org/TR/UNDERSTANDING-WCAG20/understanding-techniques.html#understanding-techniques">Understanding Techniques for WCAG Success Criteria</a>.</blockquote>

Pro: It's all over so can't miss it. It links to the important info.
Con: It's all over so cluttering.
Possible con: It doesn't specifically say sufficient.

Straw proposal 2a:
- Nothing in the About section.

Straw proposal 2b:
- Add to the About section: <blockquote>All techniques are informative; they are not required. <strong>Please read important information in the <a href="http://www.w3.org/TR/UNDERSTANDING-WCAG20/understanding-techniques.html#understanding-techniques ">Understanding Techniques for WCAG Success Criteria</a></strong> section of Understanding WCAG 2.0.</blockquote>

**Comment by yatil** [comment]
This was discussed in the [EOWG meeting on 2015-12-03](http://www.w3.org/2015/12/04-eo-minutes.html#item05).

**Comment by yatil** [comment]
The note is now linked from every sufficient techniques box to a note on the bottom which reflects the text that was in the previous quickref but with an attempt to shorten the information.

**Comment by shawna-slh** [comment]
[EOWG meeting minutes 2015 Dec 11](http://www.w3.org/2015/12/11-eo-minutes.html#item03)
