### ISSUE TITLE
The visual design needs polish

### ISSUE THREAD

**Issue by mitchellevan** [w3c/wai-wcag-quickref#77]
The visual design is cluttered and unrefined, especially in the main content area.
- Starting from "Principle 1 – Perceivable" and reading down through the "BACK TO TOP" link at the bottom of the first success criterion, I see 12 different typographic treatments.
- Iconography is inconsistent and adds to the clutter. Caret directions are more complex than necessary: they point in three directions. Both caret and "X" are used to signify collapsing a section. Both "i" and "?" are used to signify informative content. "i" is used both for links and for non-link text.
- Text in the main content area does not follow strong visual alignment.
- Line length has no maximum. In revisiting the layout, I wonder if you can achieve roughly the "80 characters" recommendation of SC 1.4.8 Visual Presentation (Level AAA)
- Links have too much variation of visual styling and alignment, and distract from overall readability and aesthetics.

I regret I can't give more constructive suggestions! I have the sense that design polish is definitely doable, although I lack the visual designer skills to offer a stronger direction myself.

**Comment by yatil** [comment]
I have made some changes to make the visual layout more consistent.

**Comment by davidberman** [comment]
Thumbs up on the tweaks, especially on the improvements to collapsing a section.
