### ISSUE TITLE
Keyboard focus problems with "Share this view"

### ISSUE THREAD

**Issue by mitchellevan** [w3c/wai-wcag-quickref#78]
When I click "Share this view", somehow the readonly URL is selected but not focused. Focus remains on the "Share this view" button.

When I tab to Close, then use Enter or Space to activate it, I expect focus to return to the "Share this view" button. Currently, tabbing resumes from the top of the page.

Tested with Chrome 46 on ChromeOS.

**Comment by davidberman** [comment]
This appears fixed now, when I test.

**Comment by yatil** [comment]
This was fixed in 91d7304.
