### ISSUE TITLE
Content is missing in some success criteria

### ISSUE THREAD

**Issue by mitchellevan** [w3c/wai-wcag-quickref#83]
I didn't check everything, but I happened to notice these.
- 1.3.3 Sensory Characteristics -- after "refer to", the words "Guideline 2.3" are missing.
- 1.4.2 Audio Control -- after "see", the words "Conformance Requirement 5: Non-Interference" are missing.
- 2.2.2 Pause, Stop, Hide -- in its full description, a few words are missing.
- 3.3.4 Error Prevention (Legal, Financial, Data) is missing its full description.
- 3.3.6 Error Prevention (All) is missing its full description.

**Comment by yatil** [comment]
Related to #26.

**Comment by yatil** [comment]
/me closes this item as it is covered in #26. Thanks for the heads-up.
