### ISSUE TITLE
Motion animation in the main content area is excessive

### ISSUE THREAD

**Issue by mitchellevan** [w3c/wai-wcag-quickref#85]
Current behavior:
When I click a "BACK TO TOP" link, or I click a link in the sidebar navigation, the main content area scrolls smoothly with easing.
Seen in Chrome 46 on ChromeOS.

Problem (in my opinion):
- I find this motion distracting, especially for large jumps.
- This motion is unnecessary for orientation, because (1) the purpose of "back to top" is clear without the animation, and (2) everything is numbered.

Recommendation:
- Option #1: Omit this scripted motion, and let each browser do its native behavior for scroll-into-view.  \* Option #2: If a sudden repositioning of the main content seems too jarring, consider a more subtle animation, such as a fading effect.

**Comment by yatil** [comment]
Suggested solution: Remove “smooth scrolling” for the back-to-top link (done in 657649d), but keep it in the sidebar to give users a sense for where they are in the document. Work on the scrolling animation timing.

**Comment by yatil** [comment]
I have changed the timing.

**Comment by davidberman** [comment]
I think it's fine now.
