### ISSUE TITLE
Needless link "How to Meet WCAG 2.0"

### ISSUE THREAD

**Issue by mitchellevan** [w3c/wai-wcag-quickref#87]
"[Draft] How to Meet WCAG 2.0" is a link which does nothing except refresh the page I'm already on.

Recommendation: Make it the level 1 heading (h1), not a link.

**Comment by yatil** [comment]
Hi @mitchellevan,
I have removed the link but didn’t change it to an H1. The title of the document is set to say the same, the text in the banner area is in a banner role and adding an H1 there would mean that all other headings would need to shift down one level. This way the H1s give direct access to the principles.

Best, Eric
