### ISSUE TITLE
The tabbed area (over, filters, tags) is not accessible to users who use browser zoom

### ISSUE THREAD

**Issue by mraccess77** [w3c/wai-wcag-quickref#9]
The tabbed area does not display correctly when browser zoom is used and it is not possible to see all content in that area as there is a snap-to-point when using the scrollbar or mouse that auto scrolls past the entire area.  These snap points can make it very difficult to access text that doesn't fit in the current view as when you try to scroll to it you are taken past that section of the page.   The fixed header could possible also play a factor in this.  Thanks!

**Comment by yatil** [comment]
Hi Jon, thanks for the heads up. We’re currently using bootstrap to – well – bootstrap the development process and it has its flaws. We expect to get to remove most of those flaws. We are also in the process of re-juggling the content to make it work better. For example we have removed the tabbed interface.

**Comment by mraccess77** [comment]
This has gotten much better.  But I am still running into issues after zooming in and out to 200% that the hide button appears halfway off the ledge of the screen at different points.  I was using Chrome at 1024x768 and at 800x600 on Windows 7.

**Comment by yatil** [comment]
Still working on it :-)

**Comment by yatil** [comment]
I think this got fixed somewhere along the way, at least the hide button works like I’d expect it to work with zoom.
