### ISSUE TITLE
Filters feedback - tags and technologies

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-wcag-quickref#94]
Sharron & I did some informal usability testing at a recent conference, and here's some input we received or observed:
1. In the Tags section, looking for "alt text".
2. In the Technologies section, suggested removing unpopular technologies, including Flash, Silverlight, and one of the scriptings.

My thoughts on these:
1. Don't add it. It wouldn't show much, and would be redundant with images, etc.
2. Probably we want to leave them since we have them, but I think we want to re-order the list. Either most common & most important for accessibility & W3C technologies higher, or ABC order. Straw proposal for the first:
HTML
CSS
ARIA
C-s scripting
S-s scripting
SMIL
PDF
Flash
Silverlight

(Note that I think we change "WAI-ARIA -> "ARIA" partly since that's the label on the techniques.)

**Comment by yatil** [comment]
I wonder how much leeway we have with the WAI- prefix on ARIA, there was an IP reason for the WAI- prefix afaik.

In this vein, should we consider renaming Client-side scripting to JavaScript?

**Comment by shawna-slh** [comment]
Re: WAI-ARIA -> ARIA. You are correct about issue, e.g., http://www.w3.org/WAI/aria/faq#justaria
I'm pretty knowledgeable about the whole issue and I am comfortable in this case using just ARIA. Again, that's what the Techniques are called

I'm not knowledgeable about issues surrounding Client-side scripting -> JavaScript. But anyway, WCAG uses "Client-side scripting" http://www.w3.org/WAI/GL/WCAG20-TECHS/#contents so I [mildly] vote to just leave it... or possibly "Client-side scripting (JavaScript)" but that's probably not worth the clutter.
